[[Samples]]
== Samples

To import a semple add a new profile on the Bellog homepage by clicking on the '+' card. +
Then select "Import Profile" and press "Save".

*By default all drivers of samples are set to 'Clipboard'. If you want to use a COM port edit the profile and change the driver.*

[[App_Log_Template]]
=== App Log Template

Tracks the errors on a separate logs and highlights messages with prefix "info, warning, error".

[[Json_Lint]]
=== JsonLint

Paste a Json object and see it formatted and highlighted.

[[Iot_Log]]
=== Iot Log

Converts CBOR messages received from an MQTT transport into a JSON readable format. You can print CBOR from a device since it is lightweight to print.
It then tracks heaps allocation in a separate view.

See link:./Iot_Log_Sample.txt[Iot_Log_Sample.txt] and paste the content into Bellog runtime.

[[Serial_Protocol]]
=== Serial Protocol

Send and Receive raw binary packets with the following format:


[width="100%",options="header,footer"]
|====================
| Byte 0 | Byte 1 | ... | Byte N-2 | Byte N-1 | Byte N
^| CMD | Data len | Data 2.1+^| CRC16 | 0xF5
|====================

*Note:* This is an example. A real protocol has at least some byte stuffing.

[[Contributions]]
=== Contributions

Please make a Pull Request if you have a sample to share or improve.